version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
