version: '3.8'

services:
  bot:
    image: ghcr.io/barbashov/telegram_summarize_bot:main
    pull_policy: always
    container_name: telegram_summarize_bot
    restart: unless-stopped
    volumes:
      - bot_data:/app/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: telegram_summarize_bot --interval 60 --cleanup

  qdrant:
    image: qdrant/qdrant:v1.13.2
    profiles: ["rag"]
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot_data:
    driver: local
  qdrant_data:
    driver: local
